### ISSUE TITLE
best_models directory does not exists

### ISSUE THREAD

**Issue by ShawnBIT** [spytensor/detect_steel_bar#2]
It seems that in the main.py line 184, you copy the model.pt before make the dir 'best models'. I am wondering whether you should add the follow code at line 115.
`if not os.path.exists('best_models'):
       os.makedirs('best_models')
`

**Comment by spytensor** [comment]
@ShawnBIT Thanks for your reminding，I'll solve it.

**Comment by monkeyking** [comment]
You can create a folder named 'best_models' under directory detect_steel_bar. @ShawnBIT

**Comment by ShawnBIT** [comment]
@monkeyking I created the folder 'best_models' when I found the bug. I just wanna make the source code more stable for anyone who runs it the first time like me. Anyway, thanks for your solution.

**Comment by monkeyking** [comment]
HaHa my careless!!HAHAHAHAHAHA

**Comment by leidaguo** [comment]
gilivable!
