### ISSUE TITLE
something about  data enhancement processing

### ISSUE THREAD

**Issue by 17764591637** [spytensor/detect_steel_bar#3]
hi，big old！How to do some data enhancement processing on the training picture, I found that increasing the size of the input picture will also lead to missed detection or misdetection.There are some fake targets that are really no different from real goals. This is really difficult to deal with.

**Comment by monkeyking** [comment]
@17764591637 hahahahaha ni are funny ,can`t help laughing

**Comment by monkeyking** [comment]
Histogram Equalization，sharpening，and some other method can be considered! It`s a image processing problem.
@17764591637

**Comment by spytensor** [comment]
@17764591637  see this https://github.com/Paperspace/DataAugmentationForObjectDetection

**Comment by 17764591637** [comment]
thanks！
