### ISSUE TITLE
CUDA error: out of memory？

### ISSUE THREAD

**Issue by FakerYFX** [spytensor/detect_steel_bar#4]
我用的P100的卡，做了数据增强，出现这个error，CUDA error: out of memory。有啥解决办法不？
@spytensor

**Comment by spytensor** [comment]
图片尺寸和模型不要太大，另外检查一下增强后的格式是否正确，我之前也出现过类似错误，是由于将多张图片的标签弄到了一张图

**Comment by FakerYFX** [comment]
好的，多谢，我检查一下

**Comment by miaomi1994** [comment]
I meet the same problem,but I use resnet18 and image'size is 800*1000,so I don't know why out of memory,I use GTX1080ti

**Comment by miaomi1994** [comment]
I meet the same problem,but I use resnet18 and image'size is 800*1000,so I don't know why out of memory,I use GTX1080ti @spytensor @xieyufei1993
