### ISSUE TITLE
请问在voc数据集上测试过这代码的性能吗？

### ISSUE THREAD

**Issue by pengfeidip** [spytensor/detect_steel_bar#7]
请问在voc数据集上测试过这代码的性能吗？。。。

**Comment by pengfeidip** [comment]
已邮件联系作者，未在公开数据集上测试此性能

**Comment by huangshenneng** [comment]
请问，有window版本的吗？torch.utils.ffi is deprecated. Please use cpp extensions instead，请问您的pytorch是什么版本的？
