### ISSUE TITLE
您好，这个文件是怎么生成的，怎么找不到？

### ISSUE THREAD

**Issue by zhenkai996icu** [spytensor/detect_steel_bar#9]
Traceback (most recent call last):
  File "retinanet/predict.py", line 26, in <module>
       results_file = open("./submit/larger%s.csv"%str(threshold),"w")
FileNotFoundError: [Errno 2] No such file or directory: './submit/larger0.5.csv'

**Comment by spytensor** [comment]
这是没有"./submit/"文件夹,创建一下就ok了

**Comment by zhenkai996icu** [comment]
好的，谢谢


| |
13602854966
|
|
13602854966@163.com
|
签名由网易邮箱大师定制
在2019年5月24日 11:16，spytensor<notifications@github.com> 写道：

这是没有"./submit/"文件夹,创建一下就ok了
